name: Update Blog Index and Sitemap

on:
  schedule:
    - cron: '0 0,12 * * *' # Executa duas vezes por dia (meia-noite e meio-dia)
  workflow_dispatch: # Permite a execução manual

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Run update script
        run: python update_script.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html sitemap.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated update of index.html and sitemap.xml" && git push)
